# Site settings
title: Website Template
baseurl: "/os-component-website" # the subpath of your site, e.g. /blog/
                                 # usually empty. necessary for buidling absolute URIs
                                 # for metadata header
url: "https://jimmac.github.io"   # the base hostname & protocol for your site
sourceurl: "https://github.com/jimmac/os-component-website"
description: "Description of the OS Component website."
issuesurl: "https://github.com/jimmac/os-component-website/issues"
permalink: /:title/

# Build settings
markdown: kramdown
